branches:
  - master
  - develop

cache:
  pip: true

jobs:
  include:
    - name: black
      language: python
      python: 3.6
      install: pip install black
      script: black --check adroit tests

    - &code-test
      name: py3.6 - lint + tests
      python: 3.6
      language: python
      install:
        - pip install poetry
        - poetry develop
      script:
        - pylint adroit
        - pytest
    - <<: *code-test
      name: py3.5 - lint + tests
      python: 3.5

    - name: example
      language: python
      python: 3.6
      services: [ docker ]
      install:
        - pip install poetry
        - poetry develop
      script: ./example/run.sh
